---
title: "NA_heartdisease"
author: "Jelena Meyer"
date: "2023-06-19"
output: html_document
---

```{r build-loop-NA-function}

loop_NA <- function(data, criterion, pc, x, fft_df, x_stats_1){

  
# Prepare for loop:
  # Parameters:
  n_per_NA <- 10
  n_sims <- n_per_NA

# initialize data structure to collect results:
results <- data.frame(matrix(NA, nrow = 1 + n_sims, ncol = 26))

# results:
n_col <- ncol(x_stats_1)
results[1, 1:n_col] <- x_stats_1

  
# Prepare vectors as input for replace_values function:  
   # get all names of variables but exclude criterion: 
   col_names <- names(data)
   col_names <- col_names[col_names != criterion ]
  
   # build vector with NA percentage: 
   num_cols <- length(col_names)
   pc_per_row <- pc

   # create vector with that pc for number of rows:
   pc_vec <- rep(pc_per_row, times = num_cols)

   # set seed for reproducability
   set.seed(13)
  
# Loop 1: ---- 
for (i in 1:n_sims){

# Add NAs to data:
data_NA <- replace_values(data = data, 
                          cols = col_names, 
                          amount = pc_vec, 
                          replacement = NA, 
                          levels_amount = NULL)

  
# Apply tree definition to (OLD/NBW) data:
y <- FFTrees(object = x,
             tree.definitions = fft_df,
             data = data_NA, 
             quiet = TRUE, 
             do.comp = FALSE)

# Collect results:

    # a) tree performance:
    y_summary <- summary(y)
    y_stats <- y_summary$stats$train

    # b) level stats:
    y_level_stats <- y$trees$level_stats$train
    NA_stats <- y_level_stats[nrow(y_level_stats) , c(25 :30)]


# Combine:
all_data_df <- cbind(y_stats, NA_stats)
# dim(all_data_df)


# Collect results:
results[(1 + i), ] <- all_data_df

} # for loop. 

  
# After loop:

# Add column names to data frame:
names(results) <- names(all_data_df)

       
# Output: ----
return(results) # as data frame.

} # loop_NA().
```


```{r build-loop-pc-function}

# as input a vector with different pcs for which you want data:

loop_pc <- function(data, criterion, several_pcs, x, fft_df, x_stats_1){
  
  # Initialize list to store results
  results_dataframes <- vector("list", length(several_pcs))
  
  # length of vector, to know when to stop
  n <- length(several_pcs)
  
  # Loop 2:
  for (j in 1:n) {
    
    # use function loop_NA
    results_dataframes[[j]] <-loop_NA(data, criterion, several_pcs[j], x, fft_df, x_stats_1)

  } # for loop.
  
 # Output: ----
return(results_dataframes)# as list.

} # loop_pc.

    ```

```{r build-loop-datasets-function}

# as input a vector with different data sets for which you want data:

loop_datasets <- function(several_data, data_names, several_criterion, several_pcs){
  
  # Preparations:
  # length of vector, to know when to stop
  n <- length(several_data)
  
  
  # Initialize list to store results
  results_list_dataframes <- vector("list", n)
  
  
  # Loop 3:
  for (k in 1:n) {
    
  # build tree with original data for each dataset:
        # get name of data set:
        name <- data_names[k]

        #Build tree for normal data set:
        x <- FFTrees(formula = as.formula(paste(several_criterion[k],"~.")),
             data = several_data[[k]],
             main = name,
             goal = "bacc",
             goal.chase = "bacc",
             goal.threshold = "bacc")

        # Performance:
         x_summary <- summary(x)
         x_stats_1 <- x_summary$stats$train[1, ]

        # get tree definitions;
        x_fft_df <- get_fft_df(x)
        fft_df <- x_fft_df[1, ]  # best training tree


  
  # use function loop_NA
  results_list_dataframes[[k]] <-loop_pc(several_data[[k]], several_criterion[k], several_pcs, x, fft_df, x_stats_1)
  
 } # for loop.
  
# Output: ----
return(results_list_dataframes) # as list.

} # loop_datasets.

    ```

# Test ----



```{r TEST-function-loop-datasets}

test <- loop_datasets(several_data = list(heartdisease, titanic), 
              data_names = c("heartdisease", "titanic"), 
              several_criterion = c("diagnosis", "survived"), 
              several_pcs = c(0.25))

```






# Checks and old code ----


```{r Preparations}

# get name of data set:
get_object_name <- function(x){
  deparse(substitute(x))
}

# Check:
#get_object_name(heartdisease)
```


```{r Get-tree-for-original-data}

#Build tree for normal data set:
x <- FFTrees(formula = diagnosis ~.,
             data = heartdisease,
             main = get_object_name(heartdisease),
             goal = "bacc",
             goal.chase = "bacc",
             goal.threshold = "bacc")

# Performance:
x_summary <- summary(x)
x_stats_1 <- x_summary$stats$train[1, ]
# x_stats_1

# get tree definitions;
x_fft_df <- get_fft_df(x)
fft_df <- x_fft_df[1, ]  # best training tree
```

```{r apply-loop-function-25-na}
# use loop-NA-function, input = 25% NAs:
heart_NA_25 <- loop_NA(heartdisease, "diagnosis", 0.25)
```

```{r apply-loop-function-50-na}
# use loop-NA-function, input = 50% NAs:
heart_NA_50 <- loop_NA(heartdisease, "diagnosis", 0.50)
```

```{r apply-loop-function-75-na}
# use loop-NA-function, input = 75% NAs:
heart_NA_75 <- loop_NA(heartdisease, "diagnosis", 0.75)
```

```{r apply-loop-function-100-na}
# how many rows are in the data set:
n <- nrow(heartdisease)

# use loop-NA-function, input = 100% NAs:
heart_NA_100 <- loop_NA(heartdisease, "diagnosis", n)
```



```{r CHECK-functionality-function}
# use loop-NA-function, input = 25% NAs:
heart_NA_25 <- loop_NA(heartdisease, "diagnosis", 0.25)


# use loop-NA-function, input = 50% NAs:
heart_NA_50 <- loop_NA(heartdisease, "diagnosis", 0.50)

# use loop-NA-function, input = 75% NAs:
heart_NA_75 <- loop_NA(heartdisease, "diagnosis", 0.75)

# use loop-pc-function, input = 25, 50, 75 % NAs:
df_heart_NA <- loop_pc(heartdisease, "diagnosis", c(0.25, 0.5, 0.75))



# check:
df1 <- df_heart_NA[[1]]

all.equal(df1, heart_NA_25)

# check:
df2 <- df_heart_NA[[2]]

all.equal(df2, heart_NA_50)



# check:
df3 <- df_heart_NA[[3]]

all.equal(df3, heart_NA_75)
```

